; Auto-generated. Do not edit!


(cl:in-package tutorial_pkg-msg)


;//! \htmlinclude DoDishesGoal.msg.html

(cl:defclass <DoDishesGoal> (roslisp-msg-protocol:ros-message)
  ((dishwasher_id
    :reader dishwasher_id
    :initarg :dishwasher_id
    :type cl:integer
    :initform 0))
)

(cl:defclass DoDishesGoal (<DoDishesGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DoDishesGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DoDishesGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tutorial_pkg-msg:<DoDishesGoal> is deprecated: use tutorial_pkg-msg:DoDishesGoal instead.")))

(cl:ensure-generic-function 'dishwasher_id-val :lambda-list '(m))
(cl:defmethod dishwasher_id-val ((m <DoDishesGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tutorial_pkg-msg:dishwasher_id-val is deprecated.  Use tutorial_pkg-msg:dishwasher_id instead.")
  (dishwasher_id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DoDishesGoal>) ostream)
  "Serializes a message object of type '<DoDishesGoal>"
  (cl:let* ((signed (cl:slot-value msg 'dishwasher_id)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DoDishesGoal>) istream)
  "Deserializes a message object of type '<DoDishesGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'dishwasher_id) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DoDishesGoal>)))
  "Returns string type for a message object of type '<DoDishesGoal>"
  "tutorial_pkg/DoDishesGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DoDishesGoal)))
  "Returns string type for a message object of type 'DoDishesGoal"
  "tutorial_pkg/DoDishesGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DoDishesGoal>)))
  "Returns md5sum for a message object of type '<DoDishesGoal>"
  "d4757b44b198f8f290eb8a424780d97c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DoDishesGoal)))
  "Returns md5sum for a message object of type 'DoDishesGoal"
  "d4757b44b198f8f290eb8a424780d97c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DoDishesGoal>)))
  "Returns full string definition for message of type '<DoDishesGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal (dữ liệu gửi đi)~%int32 dishwasher_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DoDishesGoal)))
  "Returns full string definition for message of type 'DoDishesGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal (dữ liệu gửi đi)~%int32 dishwasher_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DoDishesGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DoDishesGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'DoDishesGoal
    (cl:cons ':dishwasher_id (dishwasher_id msg))
))
