// Generated by gencpp from file tutorial_pkg/DoDishesResult.msg
// DO NOT EDIT!


#ifndef TUTORIAL_PKG_MESSAGE_DODISHESRESULT_H
#define TUTORIAL_PKG_MESSAGE_DODISHESRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tutorial_pkg
{
template <class ContainerAllocator>
struct DoDishesResult_
{
  typedef DoDishesResult_<ContainerAllocator> Type;

  DoDishesResult_()
    : total_dishes_cleaned(0)  {
    }
  DoDishesResult_(const ContainerAllocator& _alloc)
    : total_dishes_cleaned(0)  {
  (void)_alloc;
    }



   typedef int32_t _total_dishes_cleaned_type;
  _total_dishes_cleaned_type total_dishes_cleaned;





  typedef boost::shared_ptr< ::tutorial_pkg::DoDishesResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorial_pkg::DoDishesResult_<ContainerAllocator> const> ConstPtr;

}; // struct DoDishesResult_

typedef ::tutorial_pkg::DoDishesResult_<std::allocator<void> > DoDishesResult;

typedef boost::shared_ptr< ::tutorial_pkg::DoDishesResult > DoDishesResultPtr;
typedef boost::shared_ptr< ::tutorial_pkg::DoDishesResult const> DoDishesResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorial_pkg::DoDishesResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorial_pkg::DoDishesResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tutorial_pkg::DoDishesResult_<ContainerAllocator1> & lhs, const ::tutorial_pkg::DoDishesResult_<ContainerAllocator2> & rhs)
{
  return lhs.total_dishes_cleaned == rhs.total_dishes_cleaned;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tutorial_pkg::DoDishesResult_<ContainerAllocator1> & lhs, const ::tutorial_pkg::DoDishesResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tutorial_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tutorial_pkg::DoDishesResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_pkg::DoDishesResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_pkg::DoDishesResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_pkg::DoDishesResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_pkg::DoDishesResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_pkg::DoDishesResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorial_pkg::DoDishesResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65b06906f7c5d0c26e4d79da0d1da640";
  }

  static const char* value(const ::tutorial_pkg::DoDishesResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65b06906f7c5d0c2ULL;
  static const uint64_t static_value2 = 0x6e4d79da0d1da640ULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorial_pkg::DoDishesResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorial_pkg/DoDishesResult";
  }

  static const char* value(const ::tutorial_pkg::DoDishesResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorial_pkg::DoDishesResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result (kết quả trả về)\n"
"int32 total_dishes_cleaned\n"
;
  }

  static const char* value(const ::tutorial_pkg::DoDishesResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorial_pkg::DoDishesResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total_dishes_cleaned);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoDishesResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorial_pkg::DoDishesResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorial_pkg::DoDishesResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "total_dishes_cleaned: ";
    Printer<int32_t>::stream(s, indent + "  ", v.total_dishes_cleaned);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIAL_PKG_MESSAGE_DODISHESRESULT_H
