// Generated by gencpp from file tutorial_pkg/DoDishesGoal.msg
// DO NOT EDIT!


#ifndef TUTORIAL_PKG_MESSAGE_DODISHESGOAL_H
#define TUTORIAL_PKG_MESSAGE_DODISHESGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tutorial_pkg
{
template <class ContainerAllocator>
struct DoDishesGoal_
{
  typedef DoDishesGoal_<ContainerAllocator> Type;

  DoDishesGoal_()
    : dishwasher_id(0)  {
    }
  DoDishesGoal_(const ContainerAllocator& _alloc)
    : dishwasher_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _dishwasher_id_type;
  _dishwasher_id_type dishwasher_id;





  typedef boost::shared_ptr< ::tutorial_pkg::DoDishesGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorial_pkg::DoDishesGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DoDishesGoal_

typedef ::tutorial_pkg::DoDishesGoal_<std::allocator<void> > DoDishesGoal;

typedef boost::shared_ptr< ::tutorial_pkg::DoDishesGoal > DoDishesGoalPtr;
typedef boost::shared_ptr< ::tutorial_pkg::DoDishesGoal const> DoDishesGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorial_pkg::DoDishesGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorial_pkg::DoDishesGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tutorial_pkg::DoDishesGoal_<ContainerAllocator1> & lhs, const ::tutorial_pkg::DoDishesGoal_<ContainerAllocator2> & rhs)
{
  return lhs.dishwasher_id == rhs.dishwasher_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tutorial_pkg::DoDishesGoal_<ContainerAllocator1> & lhs, const ::tutorial_pkg::DoDishesGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tutorial_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tutorial_pkg::DoDishesGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_pkg::DoDishesGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_pkg::DoDishesGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_pkg::DoDishesGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_pkg::DoDishesGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_pkg::DoDishesGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorial_pkg::DoDishesGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d4757b44b198f8f290eb8a424780d97c";
  }

  static const char* value(const ::tutorial_pkg::DoDishesGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd4757b44b198f8f2ULL;
  static const uint64_t static_value2 = 0x90eb8a424780d97cULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorial_pkg::DoDishesGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorial_pkg/DoDishesGoal";
  }

  static const char* value(const ::tutorial_pkg::DoDishesGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorial_pkg::DoDishesGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal (dữ liệu gửi đi)\n"
"int32 dishwasher_id\n"
;
  }

  static const char* value(const ::tutorial_pkg::DoDishesGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorial_pkg::DoDishesGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dishwasher_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoDishesGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorial_pkg::DoDishesGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorial_pkg::DoDishesGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "dishwasher_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.dishwasher_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIAL_PKG_MESSAGE_DODISHESGOAL_H
